version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: mvn clean package

      - run: mvn integration-test
      
  deploy:
    docker: 
      - image: circleci/openjdk:8-jdk
      
    working_directory: ~/repo
    
    steps:
      - add_ssh_keys
      
      - checkout

      - run: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - maven-repo
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master